name: Deploy to EC2

on:
  push:
    branches:
      - master  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Copy files to EC2
      env:
        KEY: ${{ secrets.AWS_KEY }}
        HOST: ${{ secrets.AWS_HOST }}
        USER: ec2-user
      run: |
        scp -i $KEY -r * $USER@$HOST:/home/ec2-user/book_management

    - name: SSH into EC2 and deploy
      env:
        KEY: ${{ secrets.AWS_KEY }}
        HOST: ${{ secrets.AWS_HOST }}
        USER: ec2-user
      run: |
        ssh -i $KEY $USER@$HOST << 'EOF'
        cd /home/ec2-user/book_management
        source venv/bin/activate
        uvicorn main:app --host 0.0.0.0 --port 8000
        EOF
